export type Grade = "A+" | "A" | "A-" | "B+" | "B" | "B-" | "C+" | "C" | "C-";

export interface ListingItem {
  id: number;
  title: string;
  price: number;
  priceLabel: string;
  grade: Grade;
  year: number;
  month: number;
  region: string;
  hours: string;
  images: string[];
  href: string;
  createdAt: string;
  manufacturer: string;
  model: string;
  category: string;
  categorySlug: string;
  isVip?: boolean;
  // Detail fields
  type: "매매" | "대여" | "급매";
  engine: string;
  transmission: string;
  tonnage: string;
  payment: string;
  usageUnit: "KM" | "HR";
  undercarriageType: string;
  undercarriageCondition: string;
  companyName: string;
  contact: string;
  youtubeUrl: string;
  description: string;
  listingType: "무료" | "유료";
}

const IMG = [
  "https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1621922688758-8d99e2bead70?q=80&w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1580901368919-7738efb0f228?q=80&w=800&auto=format&fit=crop",
];

function imgs(start: number, count = 4) {
  return Array.from({ length: count }, (_, i) => IMG[(start + i) % IMG.length]);
}

export const MOCK_LISTINGS: ListingItem[] = [
  // ═══ excavator VIP ═══
  {
    id: 1,
    title: "현대 HX220 굴삭기",
    price: 7500,
    priceLabel: "7,500만원",
    grade: "A+",
    year: 2022,
    month: 5,
    region: "경기",
    hours: "2,100HR",
    images: imgs(0, 5),
    href: "/listings/1",
    createdAt: "2025-01-15",
    manufacturer: "현대",
    model: "HX220",
    category: "굴삭기",
    categorySlug: "excavator",
    isVip: true,
    type: "매매",
    engine: "170",
    transmission: "자동",
    tonnage: "22",
    payment: "협의",
    undercarriageType: "철(STEEL)",
    undercarriageCondition: "상",
    usageUnit: "HR",
    companyName: "중기나라",
    contact: "010-1234-5678",
    youtubeUrl: "",
    description:
      "현대 HX220 굴삭기 2022년식입니다. 상태 최상급이며, 정비 이력 완벽합니다. 원오너 장비이며, 주로 도심지 건축현장에서 사용했습니다. 하부 90% 이상, 엔진 컨디션 좋습니다. 직접 보시고 판단해주세요.",
    listingType: "무료",
  },
  {
    id: 2,
    title: "두산 DX225 굴삭기",
    price: 6800,
    priceLabel: "6,800만원",
    grade: "A",
    year: 2021,
    month: 3,
    region: "충남",
    hours: "3,500HR",
    images: imgs(1, 4),
    href: "/listings/2",
    createdAt: "2025-01-14",
    manufacturer: "두산",
    model: "DX225LC",
    category: "굴삭기",
    categorySlug: "excavator",
    isVip: true,
    type: "매매",
    engine: "165",
    transmission: "자동",
    tonnage: "22.5",
    payment: "할부",
    undercarriageType: "철(STEEL)",
    undercarriageCondition: "상",
    usageUnit: "HR",
    companyName: "충남중기",
    contact: "010-2345-6789",
    youtubeUrl: "",
    description:
      "두산 DX225LC 정품입니다. 엔진 오버홀 완료, 유압 시스템 점검 완료. 하부 80% 이상 남아있습니다. 현장에서 바로 투입 가능한 상태입니다.",
    listingType: "무료",
  },
  {
    id: 3,
    title: "코벨코 SK200 굴삭기",
    price: 9500,
    priceLabel: "9,500만원",
    grade: "A+",
    year: 2023,
    month: 1,
    region: "서울",
    hours: "1,200HR",
    images: imgs(2, 5),
    href: "/listings/3",
    createdAt: "2025-01-13",
    manufacturer: "코벨코",
    model: "SK200-10",
    category: "굴삭기",
    categorySlug: "excavator",
    isVip: true,
    type: "매매",
    engine: "155",
    transmission: "자동",
    tonnage: "20",
    payment: "현금",
    undercarriageType: "철(STEEL)",
    undercarriageCondition: "상",
    usageUnit: "HR",
    companyName: "서울건기",
    contact: "010-3456-7890",
    youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    description:
      "코벨코 SK200-10 최신형. 거의 새 장비 수준입니다. 실시간 사용 1,200시간. 고장 이력 전무합니다. 연비 우수하고 소음 적은 모델입니다.",
    listingType: "무료",
  },
  {
    id: 4,
    title: "CAT 320GC 굴삭기",
    price: 8800,
    priceLabel: "8,800만원",
    grade: "A",
    year: 2022,
    month: 8,
    region: "경기",
    hours: "2,800HR",
    images: imgs(3, 4),
    href: "/listings/4",
    createdAt: "2025-01-12",
    manufacturer: "CAT",
    model: "320GC",
    category: "굴삭기",
    categorySlug: "excavator",
    isVip: true,
    type: "매매",
    engine: "162",
    transmission: "자동",
    tonnage: "22",
    payment: "협의",
    undercarriageType: "철(STEEL)",
    undercarriageCondition: "상",
    usageUnit: "HR",
    companyName: "캣코리아",
    contact: "010-4567-8901",
    youtubeUrl: "",
    description:
      "CAT 320GC 캐터필라 굴삭기. 정품 수입 장비이며 CAT 공식 정비센터에서 관리한 장비입니다. 연료 효율 뛰어나고 작업 속도 빠릅니다.",
    listingType: "무료",
  },
  // ═══ excavator Regular ═══
  {
    id: 5,
    title: "히타치 ZX210 굴삭기",
    price: 5500,
    priceLabel: "5,500만원",
    grade: "B+",
    year: 2019,
    month: 11,
    region: "경남",
    hours: "5,800HR",
    images: imgs(4, 3),
    href: "/listings/5",
    createdAt: "2025-01-11",
    manufacturer: "히타치",
    model: "ZX210LC-5",
    category: "굴삭기",
    categorySlug: "excavator",
    type: "매매",
    engine: "158",
    transmission: "자동",
    tonnage: "21",
    payment: "할부",
    undercarriageType: "철(STEEL)",
    undercarriageCondition: "중",
    usageUnit: "HR",
    companyName: "경남장비",
    contact: "010-5678-9012",
    youtubeUrl: "",
    description:
      "히타치 ZX210LC-5 굴삭기입니다. 사용감 있으나 전체적으로 양호한 상태. 정기 점검 받은 장비입니다.",
    listingType: "무료",
  },
  {
    id: 6,
    title: "볼보 EC210 굴삭기",
    price: 7200,
    priceLabel: "7,200만원",
    grade: "A-",
    year: 2020,
    month: 6,
    region: "전북",
    hours: "4,100HR",
    images: imgs(0, 4),
    href: "/listings/6",
    createdAt: "2025-01-10",
    manufacturer: "볼보",
    model: "EC210D",
    category: "굴삭기",
    categorySlug: "excavator",
    type: "매매",
    engine: "160",
    transmission: "자동",
    tonnage: "21.5",
    payment: "협의",
    undercarriageType: "철(STEEL)",
    undercarriageCondition: "상",
    usageUnit: "HR",
    companyName: "전북중장비",
    contact: "010-6789-0123",
    youtubeUrl: "",
    description:
      "볼보 EC210D 굴삭기. 볼보 특유의 내구성과 연비 효율이 좋은 모델입니다. 하부 상태 양호합니다.",
    listingType: "유료",
  },
  {
    id: 7,
    title: "현대 R260LC 굴삭기",
    price: 4800,
    priceLabel: "4,800만원",
    grade: "B",
    year: 2018,
    month: 2,
    region: "충북",
    hours: "7,200HR",
    images: imgs(1, 3),
    href: "/listings/7",
    createdAt: "2025-01-09",
    manufacturer: "현대",
    model: "R260LC-9S",
    category: "굴삭기",
    categorySlug: "excavator",
    type: "매매",
    engine: "190",
    transmission: "자동",
    tonnage: "26",
    payment: "현금",
    undercarriageType: "철(STEEL)",
    undercarriageCondition: "중",
    usageUnit: "HR",
    companyName: "충북건기",
    contact: "010-7890-1234",
    youtubeUrl: "",
    description:
      "현대 R260LC 굴삭기 26톤급. 토목 현장에서 주로 사용. 가격 대비 성능 좋은 장비입니다.",
    listingType: "무료",
  },
  {
    id: 8,
    title: "두산 DX140 미니굴삭기",
    price: 3200,
    priceLabel: "3,200만원",
    grade: "B+",
    year: 2020,
    month: 4,
    region: "대전",
    hours: "3,900HR",
    images: imgs(2, 4),
    href: "/listings/8",
    createdAt: "2025-01-08",
    manufacturer: "두산",
    model: "DX140LC",
    category: "굴삭기",
    categorySlug: "excavator",
    type: "매매",
    engine: "98",
    transmission: "자동",
    tonnage: "14",
    payment: "할부",
    undercarriageType: "철(STEEL)",
    undercarriageCondition: "상",
    usageUnit: "HR",
    companyName: "대전장비",
    contact: "010-8901-2345",
    youtubeUrl: "",
    description:
      "두산 DX140LC 미니굴삭기. 좁은 현장에서도 활용 가능한 소형 장비입니다. 관리 잘 된 장비.",
    listingType: "무료",
  },
  {
    id: 9,
    title: "현대 R55W 타이어식 굴삭기",
    price: 2800,
    priceLabel: "2,800만원",
    grade: "A",
    year: 2021,
    month: 9,
    region: "인천",
    hours: "2,500HR",
    images: imgs(3, 3),
    href: "/listings/9",
    createdAt: "2025-01-07",
    manufacturer: "현대",
    model: "R55W-9S",
    category: "굴삭기",
    categorySlug: "excavator",
    type: "매매",
    engine: "48",
    transmission: "자동",
    tonnage: "5.5",
    payment: "현금",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "상",
    usageUnit: "HR",
    companyName: "인천미니",
    contact: "010-9012-3456",
    youtubeUrl: "",
    description:
      "타이어식 미니 굴삭기입니다. 도로 이동 편리하고 다용도로 활용 가능합니다.",
    listingType: "무료",
  },
  {
    id: 10,
    title: "코벨코 SK55 미니굴삭기",
    price: 2400,
    priceLabel: "2,400만원",
    grade: "B+",
    year: 2019,
    month: 7,
    region: "강원",
    hours: "4,300HR",
    images: imgs(4, 3),
    href: "/listings/10",
    createdAt: "2025-01-06",
    manufacturer: "코벨코",
    model: "SK55SRX",
    category: "굴삭기",
    categorySlug: "excavator",
    type: "급매",
    engine: "40",
    transmission: "자동",
    tonnage: "5.5",
    payment: "협의",
    undercarriageType: "고무(RUBBER)",
    undercarriageCondition: "중",
    usageUnit: "HR",
    companyName: "강원건기",
    contact: "010-0123-4567",
    youtubeUrl: "",
    description:
      "급매합니다. 코벨코 미니굴삭기 SK55. 소형 현장용으로 적합합니다.",
    listingType: "무료",
  },
  {
    id: 11,
    title: "CAT 305E 미니굴삭기",
    price: 3500,
    priceLabel: "3,500만원",
    grade: "A",
    year: 2022,
    month: 10,
    region: "경기",
    hours: "1,800HR",
    images: imgs(0, 4),
    href: "/listings/11",
    createdAt: "2025-01-05",
    manufacturer: "CAT",
    model: "305E2 CR",
    category: "굴삭기",
    categorySlug: "excavator",
    type: "매매",
    engine: "44",
    transmission: "자동",
    tonnage: "5",
    payment: "할부",
    undercarriageType: "고무(RUBBER)",
    undercarriageCondition: "상",
    usageUnit: "HR",
    companyName: "미니캣",
    contact: "010-1111-2222",
    youtubeUrl: "",
    description:
      "CAT 305E2 미니굴삭기. 캐터필라 정품으로 내구성 우수합니다. 고무 트랙 상태 좋습니다.",
    listingType: "무료",
  },
  {
    id: 12,
    title: "히타치 ZX85 굴삭기",
    price: 4100,
    priceLabel: "4,100만원",
    grade: "A-",
    year: 2020,
    month: 12,
    region: "부산",
    hours: "3,600HR",
    images: imgs(1, 4),
    href: "/listings/12",
    createdAt: "2025-01-04",
    manufacturer: "히타치",
    model: "ZX85USB-5",
    category: "굴삭기",
    categorySlug: "excavator",
    type: "매매",
    engine: "65",
    transmission: "자동",
    tonnage: "8.5",
    payment: "협의",
    undercarriageType: "철(STEEL)",
    undercarriageCondition: "상",
    usageUnit: "HR",
    companyName: "부산중기",
    contact: "010-3333-4444",
    youtubeUrl: "",
    description:
      "히타치 ZX85 중소형 굴삭기. 다목적 활용 가능하며 연비 좋은 장비입니다.",
    listingType: "유료",
  },
  {
    id: 13,
    title: "현대 HW210 타이어식",
    price: 6200,
    priceLabel: "6,200만원",
    grade: "A",
    year: 2021,
    month: 5,
    region: "경기",
    hours: "3,100HR",
    images: imgs(2, 3),
    href: "/listings/13",
    createdAt: "2025-01-03",
    manufacturer: "현대",
    model: "HW210",
    category: "굴삭기",
    categorySlug: "excavator",
    type: "매매",
    engine: "158",
    transmission: "자동",
    tonnage: "21",
    payment: "할부",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "상",
    usageUnit: "HR",
    companyName: "경기타이어",
    contact: "010-5555-6666",
    youtubeUrl: "",
    description:
      "현대 HW210 타이어식 굴삭기. 도로 이동 용이하고 작업 효율 높습니다.",
    listingType: "유료",
  },
  {
    id: 14,
    title: "두산 DX300 굴삭기",
    price: 11000,
    priceLabel: "1억 1,000만원",
    grade: "A+",
    year: 2023,
    month: 2,
    region: "충남",
    hours: "980HR",
    images: imgs(3, 5),
    href: "/listings/14",
    createdAt: "2025-01-02",
    manufacturer: "두산",
    model: "DX300LC-7",
    category: "굴삭기",
    categorySlug: "excavator",
    type: "매매",
    engine: "217",
    transmission: "자동",
    tonnage: "30",
    payment: "협의",
    undercarriageType: "철(STEEL)",
    undercarriageCondition: "상",
    usageUnit: "HR",
    companyName: "충남대형",
    contact: "010-7777-8888",
    youtubeUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    description:
      "두산 DX300LC 30톤급 대형 굴삭기. 거의 새 장비 수준. 대형 토목현장 투입 즉시 가능합니다.",
    listingType: "유료",
  },
  {
    id: 15,
    title: "볼보 EC140 굴삭기",
    price: 3900,
    priceLabel: "3,900만원",
    grade: "B+",
    year: 2019,
    month: 8,
    region: "전남",
    hours: "5,200HR",
    images: imgs(4, 3),
    href: "/listings/15",
    createdAt: "2025-01-01",
    manufacturer: "볼보",
    model: "EC140E",
    category: "굴삭기",
    categorySlug: "excavator",
    type: "매매",
    engine: "97",
    transmission: "자동",
    tonnage: "14.5",
    payment: "현금",
    undercarriageType: "철(STEEL)",
    undercarriageCondition: "중",
    usageUnit: "HR",
    companyName: "전남중기",
    contact: "010-9999-0000",
    youtubeUrl: "",
    description:
      "볼보 EC140E 소형 굴삭기. 볼보 특유의 안정성과 내구성을 갖춘 장비입니다.",
    listingType: "무료",
  },
  {
    id: 16,
    title: "코벨코 SK260 굴삭기",
    price: 5800,
    priceLabel: "5,800만원",
    grade: "A-",
    year: 2020,
    month: 11,
    region: "대구",
    hours: "4,500HR",
    images: imgs(0, 4),
    href: "/listings/16",
    createdAt: "2024-12-30",
    manufacturer: "코벨코",
    model: "SK260LC-10",
    category: "굴삭기",
    categorySlug: "excavator",
    type: "매매",
    engine: "186",
    transmission: "자동",
    tonnage: "26",
    payment: "할부",
    undercarriageType: "철(STEEL)",
    undercarriageCondition: "중",
    usageUnit: "HR",
    companyName: "대구건기",
    contact: "010-1212-3434",
    youtubeUrl: "",
    description: "코벨코 SK260 26톤급 굴삭기. 연비 좋고 소음 적은 모델입니다.",
    listingType: "유료",
  },
  // ═══ dump-truck ═══
  {
    id: 101,
    title: "현대 뉴파워트럭 15톤 덤프",
    price: 4500,
    priceLabel: "4,500만원",
    grade: "A",
    year: 2022,
    month: 4,
    region: "경기",
    hours: "85,000KM",
    images: imgs(2, 4),
    href: "/listings/101",
    createdAt: "2025-01-15",
    manufacturer: "현대",
    model: "뉴파워트럭",
    category: "덤프트럭",
    categorySlug: "dump-truck",
    isVip: true,
    type: "매매",
    engine: "380",
    transmission: "수동",
    tonnage: "15",
    payment: "할부",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "상",
    usageUnit: "KM",
    companyName: "경기덤프",
    contact: "010-2222-3333",
    youtubeUrl: "",
    description:
      "현대 뉴파워트럭 15톤 덤프입니다. 주행거리 85,000km이며 사고 이력 없습니다.",
    listingType: "유료",
  },
  {
    id: 102,
    title: "대우 노부스 25톤 덤프",
    price: 5800,
    priceLabel: "5,800만원",
    grade: "A+",
    year: 2023,
    month: 6,
    region: "충남",
    hours: "42,000KM",
    images: imgs(3, 4),
    href: "/listings/102",
    createdAt: "2025-01-14",
    manufacturer: "대우",
    model: "노부스 SE",
    category: "덤프트럭",
    categorySlug: "dump-truck",
    isVip: true,
    type: "매매",
    engine: "420",
    transmission: "자동",
    tonnage: "25",
    payment: "현금",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "상",
    usageUnit: "KM",
    companyName: "충남트럭",
    contact: "010-4444-5555",
    youtubeUrl: "",
    description:
      "대우 노부스 25톤 덤프트럭. 2023년식 최신형으로 주행거리 짧습니다.",
    listingType: "무료",
  },
  {
    id: 103,
    title: "볼보 A30G 덤프트럭",
    price: 12000,
    priceLabel: "1억 2,000만원",
    grade: "A+",
    year: 2022,
    month: 9,
    region: "서울",
    hours: "2,100HR",
    images: imgs(0, 5),
    href: "/listings/103",
    createdAt: "2025-01-13",
    manufacturer: "볼보",
    model: "A30G",
    category: "덤프트럭",
    categorySlug: "dump-truck",
    isVip: true,
    type: "매매",
    engine: "370",
    transmission: "자동",
    tonnage: "30",
    payment: "협의",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "상",
    usageUnit: "HR",
    companyName: "서울볼보",
    contact: "010-6666-7777",
    youtubeUrl: "",
    description: "볼보 A30G 아티큘레이트 덤프트럭. 최고급 대형 장비입니다.",
    listingType: "무료",
  },
  {
    id: 104,
    title: "현대 15톤 덤프트럭",
    price: 3200,
    priceLabel: "3,200만원",
    grade: "B+",
    year: 2019,
    month: 1,
    region: "경남",
    hours: "152,000KM",
    images: imgs(1, 3),
    href: "/listings/104",
    createdAt: "2025-01-12",
    manufacturer: "현대",
    model: "뉴파워트럭",
    category: "덤프트럭",
    categorySlug: "dump-truck",
    type: "매매",
    engine: "340",
    transmission: "수동",
    tonnage: "15",
    payment: "현금",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "중",
    usageUnit: "KM",
    companyName: "경남덤프",
    contact: "010-8888-9999",
    youtubeUrl: "",
    description: "현대 15톤 덤프트럭 중고 매물입니다. 가격 대비 실용적인 장비.",
    listingType: "무료",
  },
  {
    id: 105,
    title: "대우 25톤 축덤프",
    price: 6500,
    priceLabel: "6,500만원",
    grade: "A",
    year: 2021,
    month: 7,
    region: "전남",
    hours: "98,000KM",
    images: imgs(2, 4),
    href: "/listings/105",
    createdAt: "2025-01-11",
    manufacturer: "대우",
    model: "노부스",
    category: "덤프트럭",
    categorySlug: "dump-truck",
    type: "매매",
    engine: "400",
    transmission: "자동",
    tonnage: "25",
    payment: "할부",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "상",
    usageUnit: "KM",
    companyName: "전남건설",
    contact: "010-1010-2020",
    youtubeUrl: "",
    description: "대우 25톤 축덤프. 적재량 우수하며 상태 양호합니다.",
    listingType: "무료",
  },
  {
    id: 106,
    title: "벤츠 악트로스 추레라",
    price: 8500,
    priceLabel: "8,500만원",
    grade: "A+",
    year: 2023,
    month: 3,
    region: "경기",
    hours: "35,000KM",
    images: imgs(3, 4),
    href: "/listings/106",
    createdAt: "2025-01-10",
    manufacturer: "벤츠",
    model: "악트로스",
    category: "추레라",
    categorySlug: "dump-truck",
    type: "매매",
    engine: "510",
    transmission: "자동",
    tonnage: "25",
    payment: "협의",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "상",
    usageUnit: "KM",
    companyName: "경기수입",
    contact: "010-3030-4040",
    youtubeUrl: "",
    description:
      "벤츠 악트로스 추레라. 수입 프리미엄 트럭으로 성능 최상급입니다.",
    listingType: "무료",
  },
  {
    id: 107,
    title: "타타대우 25톤 덤프",
    price: 4100,
    priceLabel: "4,100만원",
    grade: "B",
    year: 2018,
    month: 10,
    region: "울산",
    hours: "178,000KM",
    images: imgs(0, 3),
    href: "/listings/107",
    createdAt: "2025-01-09",
    manufacturer: "타타대우",
    model: "프리마",
    category: "덤프트럭",
    categorySlug: "dump-truck",
    type: "매매",
    engine: "360",
    transmission: "수동",
    tonnage: "25",
    payment: "현금",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "하",
    usageUnit: "KM",
    companyName: "울산중기",
    contact: "010-5050-6060",
    youtubeUrl: "",
    description:
      "타타대우 25톤 덤프. 실사용 가능한 상태이며 가격 협의 가능합니다.",
    listingType: "무료",
  },
  {
    id: 108,
    title: "현대 25톤 덤프트럭",
    price: 5200,
    priceLabel: "5,200만원",
    grade: "A-",
    year: 2021,
    month: 5,
    region: "인천",
    hours: "72,000KM",
    images: imgs(1, 4),
    href: "/listings/108",
    createdAt: "2025-01-08",
    manufacturer: "현대",
    model: "뉴파워트럭",
    category: "덤프트럭",
    categorySlug: "dump-truck",
    type: "매매",
    engine: "410",
    transmission: "자동",
    tonnage: "25",
    payment: "할부",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "상",
    usageUnit: "KM",
    companyName: "인천트럭",
    contact: "010-7070-8080",
    youtubeUrl: "",
    description: "현대 25톤 덤프트럭. 주행거리 적고 상태 우수합니다.",
    listingType: "유료",
  },
  // ═══ mixer-truck ═══
  {
    id: 201,
    title: "현대 HD270 믹서트럭",
    price: 4500,
    priceLabel: "4,500만원",
    grade: "A",
    year: 2021,
    month: 3,
    region: "경기",
    hours: "78,000KM",
    images: imgs(0, 4),
    href: "/listings/201",
    createdAt: "2025-01-15",
    manufacturer: "현대",
    model: "HD270",
    category: "믹서트럭",
    categorySlug: "mixer-truck",
    isVip: true,
    type: "매매",
    engine: "380",
    transmission: "자동",
    tonnage: "15",
    payment: "할부",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "상",
    usageUnit: "KM",
    companyName: "경기레미콘",
    contact: "010-1122-3344",
    youtubeUrl: "",
    description: "현대 HD270 믹서트럭. 레미콘 운송용으로 최적화된 장비입니다.",
    listingType: "무료",
  },
  {
    id: 202,
    title: "현대 52M 펌프카",
    price: 15000,
    priceLabel: "1억 5,000만원",
    grade: "A+",
    year: 2022,
    month: 7,
    region: "서울",
    hours: "12,000HR",
    images: imgs(2, 5),
    href: "/listings/202",
    createdAt: "2025-01-13",
    manufacturer: "현대",
    model: "52M",
    category: "펌프카",
    categorySlug: "mixer-truck",
    isVip: true,
    type: "매매",
    engine: "420",
    transmission: "자동",
    tonnage: "25",
    payment: "협의",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "상",
    usageUnit: "HR",
    companyName: "서울펌프",
    contact: "010-5566-7788",
    youtubeUrl: "",
    description: "현대 52M 펌프카. 대형 건축현장에 적합한 고성능 펌프카입니다.",
    listingType: "무료",
  },
  {
    id: 203,
    title: "대우 프리마 믹서트럭",
    price: 3800,
    priceLabel: "3,800만원",
    grade: "B+",
    year: 2020,
    month: 11,
    region: "충남",
    hours: "95,000KM",
    images: imgs(1, 3),
    href: "/listings/203",
    createdAt: "2025-01-14",
    manufacturer: "대우",
    model: "프리마",
    category: "믹서트럭",
    categorySlug: "mixer-truck",
    type: "매매",
    engine: "360",
    transmission: "수동",
    tonnage: "15",
    payment: "현금",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "중",
    usageUnit: "KM",
    companyName: "충남레미콘",
    contact: "010-9900-1122",
    youtubeUrl: "",
    description: "대우 프리마 믹서트럭. 실사용 가능한 상태입니다.",
    listingType: "무료",
  },
  {
    id: 204,
    title: "대우 36M 펌프카",
    price: 8500,
    priceLabel: "8,500만원",
    grade: "A",
    year: 2020,
    month: 5,
    region: "부산",
    hours: "18,000HR",
    images: imgs(3, 4),
    href: "/listings/204",
    createdAt: "2025-01-12",
    manufacturer: "대우",
    model: "36M",
    category: "펌프카",
    categorySlug: "mixer-truck",
    type: "매매",
    engine: "380",
    transmission: "자동",
    tonnage: "25",
    payment: "할부",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "상",
    usageUnit: "HR",
    companyName: "부산펌프",
    contact: "010-3344-5566",
    youtubeUrl: "",
    description: "대우 36M 펌프카. 중형 건축현장에 적합합니다.",
    listingType: "무료",
  },
  // ═══ forklift ═══
  {
    id: 301,
    title: "두산 D30S 지게차",
    price: 2300,
    priceLabel: "2,300만원",
    grade: "A",
    year: 2021,
    month: 6,
    region: "경기",
    hours: "3,200HR",
    images: imgs(1, 4),
    href: "/listings/301",
    createdAt: "2025-01-15",
    manufacturer: "두산",
    model: "D30S-9",
    category: "지게차",
    categorySlug: "forklift",
    isVip: true,
    type: "매매",
    engine: "65",
    transmission: "자동",
    tonnage: "3",
    payment: "현금",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "상",
    usageUnit: "HR",
    companyName: "경기지게차",
    contact: "010-7788-9900",
    youtubeUrl: "",
    description:
      "두산 D30S 3톤 지게차. 물류 창고용으로 적합하며 상태 양호합니다.",
    listingType: "무료",
  },
  {
    id: 302,
    title: "클라크 5톤 지게차",
    price: 3500,
    priceLabel: "3,500만원",
    grade: "A+",
    year: 2023,
    month: 2,
    region: "경기",
    hours: "1,200HR",
    images: imgs(3, 4),
    href: "/listings/302",
    createdAt: "2025-01-13",
    manufacturer: "클라크",
    model: "C50S",
    category: "지게차",
    categorySlug: "forklift",
    isVip: true,
    type: "매매",
    engine: "80",
    transmission: "자동",
    tonnage: "5",
    payment: "협의",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "상",
    usageUnit: "HR",
    companyName: "클라크코리아",
    contact: "010-1133-2244",
    youtubeUrl: "",
    description: "클라크 5톤 지게차. 거의 새 장비로 사용시간 매우 짧습니다.",
    listingType: "유료",
  },
  {
    id: 303,
    title: "현대 25D 지게차",
    price: 1800,
    priceLabel: "1,800만원",
    grade: "B+",
    year: 2019,
    month: 9,
    region: "인천",
    hours: "5,100HR",
    images: imgs(2, 3),
    href: "/listings/303",
    createdAt: "2025-01-14",
    manufacturer: "현대",
    model: "25D-9",
    category: "지게차",
    categorySlug: "forklift",
    type: "매매",
    engine: "50",
    transmission: "자동",
    tonnage: "2.5",
    payment: "현금",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "중",
    usageUnit: "HR",
    companyName: "인천물류",
    contact: "010-5577-6688",
    youtubeUrl: "",
    description: "현대 2.5톤 지게차. 가성비 좋은 중고 지게차입니다.",
    listingType: "유료",
  },
  {
    id: 304,
    title: "두산 하이랜더 7톤",
    price: 4200,
    priceLabel: "4,200만원",
    grade: "A",
    year: 2022,
    month: 4,
    region: "충남",
    hours: "2,800HR",
    images: imgs(0, 4),
    href: "/listings/304",
    createdAt: "2025-01-12",
    manufacturer: "두산",
    model: "D70S-9",
    category: "하이랜더",
    categorySlug: "forklift",
    type: "매매",
    engine: "110",
    transmission: "자동",
    tonnage: "7",
    payment: "할부",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "상",
    usageUnit: "HR",
    companyName: "충남장비",
    contact: "010-9911-2233",
    youtubeUrl: "",
    description: "두산 하이랜더 7톤. 대형 물류센터 및 건설현장에 적합합니다.",
    listingType: "무료",
  },
  {
    id: 305,
    title: "밥캣 스키드로더 S570",
    price: 3800,
    priceLabel: "3,800만원",
    grade: "A-",
    year: 2021,
    month: 8,
    region: "전북",
    hours: "2,500HR",
    images: imgs(1, 3),
    href: "/listings/305",
    createdAt: "2025-01-11",
    manufacturer: "밥캣",
    model: "S570",
    category: "스키드로더",
    categorySlug: "forklift",
    type: "매매",
    engine: "62",
    transmission: "자동",
    tonnage: "2.5",
    payment: "협의",
    undercarriageType: "타이어(WHEEL)",
    undercarriageCondition: "상",
    usageUnit: "HR",
    companyName: "전북밥캣",
    contact: "010-3355-4466",
    youtubeUrl: "",
    description: "밥캣 S570 스키드로더. 다용도 작업 장비로 활용도 높습니다.",
    listingType: "유료",
  },
];

export function getListingById(id: number): ListingItem | undefined {
  return MOCK_LISTINGS.find((l) => l.id === id);
}

export function getListingsByCategory(categorySlug: string): ListingItem[] {
  return MOCK_LISTINGS.filter((l) => l.categorySlug === categorySlug);
}

export function getRelatedListings(
  listing: ListingItem,
  limit = 4,
): ListingItem[] {
  return MOCK_LISTINGS.filter(
    (l) => l.categorySlug === listing.categorySlug && l.id !== listing.id,
  ).slice(0, limit);
}

export const gradeStyle: Record<string, string> = {
  "A+": "bg-orange-600 text-white",
  A: "bg-emerald-500 text-white",
  "A-": "bg-emerald-400 text-white",
  "B+": "bg-blue-500 text-white",
  B: "bg-neutral-500 text-white",
  "B-": "bg-neutral-400 text-white",
  "C+": "bg-neutral-300 text-neutral-700",
  C: "bg-neutral-300 text-neutral-700",
  "C-": "bg-neutral-200 text-neutral-600",
};
